### PR TITLE
changed multiple uses of divisions to saved reciprocals for multiplication

### PR DESCRIPTION
**Pull request by tresreid**

### CODE REVIEW

**Comment by areinsvo** [comment]
Thanks @tresreid for this PR and for adding the changes to all implementations. @mastino can you make sure the Kokkos versions are up-to-date with these changes? It looks like the src_complete/kokkos_src hasn't been updated in a while.

@seyonglee note that this includes some changes to the OpenMPv4 implementation as well. 
@tresreid as far as I can tell, the OpenMPv4 implementation is the only one that has NITER set to 1 instead of 5. For consistency, is that worth changing before merging this PR? Or is there a specific reason that one is set differently?

**Comment by tresreid** [comment]
The OpenMP4 version only has 1 instead of 5 because I found that version takes too long to run. If I remember correctly, @seyonglee said that the version is src_complete was not correct (or wasn't the most up-to-date version). I think what is in src_complete should be swapped for @seyonglee 's corrected version (which I don't think I have).

**Comment by brnorris03** [comment]
I think it would be better to create a separate PR for Kokkos and not hold up this one (so we can run experiments).

**Comment by areinsvo** [comment]
Thanks @tres for clarifying. I went ahead and merged, and we can make separate PRs for Kokkos and OpenMPv4 as suggested.

**Pull request merged**
