### PR TITLE
tuning bsize and ntrks, directory cleanup

### PR DESCRIPTION
**Pull request by tresreid**
Makefile cleaned up
    old versions put in backup
    added definitions for changing the bsize or ntrk values
older versions/versions not actively being worked on moved to backup
Includes a tuner to make and run different implementations varying the bsize and ntrks
includes presentation on bsize and ntrks

### CODE REVIEW

**Comment by areinsvo** [comment]
Thanks @tresreid! At some point we might also need a folder for the various test scripts, but I think for now it is fine to have everything in the top level directory. One question on the OpenACC versions: does the version you kept correspond to version 1? I seem to recall that v5 or v6 was the most performant, but I think @seyonglee was planning to test all the versions again to confirm.

**Comment by tresreid** [comment]
For the OpenAcc version, the one I kept was v1. that seemed to be the fastest for me since v5 and v6 had very large memory transfer times. I'm not sure which versions @seyonglee is actively working on. In a previous PR from seyong, v1 also had many changes, so i thought it might be possible this is the most up to date version. The past few set of results I have shown use v1.

**Comment by areinsvo** [comment]
Thanks for clarifying. I'll merge this now.

**Comment by seyonglee** [comment]
When I tested on a local V100 GPUs, OpenACC v6 was  the fastest one.
(I updated V1 to print outputs similar to the CUDA version.)

Thanks.

--
Seyong Lee
Future Tech Group @ ORNL
Email: lees2@ornl.gov
Tel: 1-865-576-3869
Home Page: http://ft.ornl.gov/~lees2/

**Pull request merged**
